services:
  frontend:
    container_name: "frontend"
    image: "node:alpine"
    user: "node"
    working_dir: "/frontend"
    volumes:
      - ./frontend:/frontend
    command: "yarn start"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SQUARE_ENVIRONMENT=$UNBOXED_SQUARE_ENVIRONMENT
      - REACT_APP_SQUARE_ACCESS_TOKEN=$UNBOXED_SQUARE_ACCESS_TOKEN
      - REACT_APP_SQUARE_LOCATION_ID=$UNBOXED_SQUARE_LOCATION_ID
      - REACT_APP_SQUARE_API_VERSION=$UNBOXED_SQUARE_API_VERSION
      - REACT_APP_OAUTH_ID=$UNBOXED_OAUTH_ID
      - REACT_APP_OAUTH_SECRET=$UNBOXED_OAUTH_SECRET
  database:
    container_name: "database"
    image: "mongo"
    volumes:
      - ./database:/db
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$UNBOXED_MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$UNBOXED_MONGODB_PASSWORD
  backend:
    container_name: "backend"
    image: "node:lts-alpine3.16"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$UNBOXED_MONGODB_USER
      - DB_PASSWORD=$UNBOXED_MONGODB_PASSWORD
      - DB_NAME=$UNBOXED_MONGODB_DATABASE
      - DB_PORT=$UNBOXED_MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true


