services:
  frontend:
    container_name: "unboxed_frontend"
    hostname: unboxed_frontend
    domainname: unboxed_frontend.local
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.build
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=$NODE_ENV
      - REACT_APP_API_ENDPOINT=$API_ENDPOINT
      - REACT_APP_MAGIC_LINK_PUBLISHABLE_API_KEY=$MAGIC_LINK_PUBLISHABLE_API_KEY
      - REACT_APP_SQUARE_LOCATION_ID=$SQUARE_LOCATION_ID
    depends_on:
      - database
      - backend
    command: start
  database:
    container_name: "unboxed_database"
    hostname: unboxed_database
    domainname: unboxed_database.local
    image: "mongo"
    # command: mongod --auth
    volumes:
      - ./database:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
  backend:
    container_name: "unboxed_backend"
    hostname: unboxed_backend
    domainname: unboxed_backend.local
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=$NODE_ENV
      - MAGIC_LINK_SECRET_KEY=$MAGIC_LINK_SECRET_KEY
      - SQUARE_SIGNATURE_KEY=$SQUARE_SIGNATURE_KEY
      - SERVER_PORT=$SERVER_PORT
      - SQUARE_ENVIRONMENT=$SQUARE_ENVIRONMENT
      - SQUARE_ACCESS_TOKEN=$SQUARE_ACCESS_TOKEN
      - SQUARE_LOCATION_ID=$SQUARE_LOCATION_ID
      - SQUARE_API_VERSION=$SQUARE_API_VERSION
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - database
    # stdin_open: true
    # tty: true
volumes:
  database:
    driver: local

