services:
  frontend:
    container_name: "unboxed_frontend"
    hostname: unboxed_frontend
    domainname: unboxed_frontend.local
    build: ./frontend
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REACT_APP_SQUARE_ENVIRONMENT=$UNBOXED_SQUARE_ENVIRONMENT
      - REACT_APP_SQUARE_ACCESS_TOKEN=$UNBOXED_SQUARE_ACCESS_TOKEN
      - REACT_APP_SQUARE_LOCATION_ID=$UNBOXED_SQUARE_LOCATION_ID
      - REACT_APP_SQUARE_API_VERSION=$UNBOXED_SQUARE_API_VERSION
      - REACT_APP_OAUTH_ID=$UNBOXED_OAUTH_ID
      - REACT_APP_OAUTH_SECRET=$UNBOXED_OAUTH_SECRET
      - PATH /frontend/node_modules/.bin:$PATH
  database:
    container_name: "unboxed_database"
    hostname: unboxed_database
    domainname: unboxed_database.local
    image: "mongo"
    volumes:
      - ./database:/db
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$UNBOXED_MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$UNBOXED_MONGODB_PASSWORD
  backend:
    container_name: "unboxed_backend"
    hostname: unboxed_backend
    domainname: unboxed_backend.local
    build: ./backend
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=$UNBOXED_SQUARE_ENVIRONMENT
      - SQUARE_ACCESS_TOKEN=$UNBOXED_SQUARE_ACCESS_TOKEN
      - SQUARE_LOCATION_ID=$UNBOXED_SQUARE_LOCATION_ID
      - SQUARE_API_VERSION=$UNBOXED_SQUARE_API_VERSION
      - DB_HOST=mongodb
      - DB_USER=$UNBOXED_MONGODB_USER
      - DB_PASSWORD=$UNBOXED_MONGODB_PASSWORD
      - DB_NAME=$UNBOXED_MONGODB_DATABASE
      - DB_PORT=$UNBOXED_MONGODB_DOCKER_PORT
    # stdin_open: true
    # tty: true


