services:
  frontend:
    container_name: "unboxed_frontend"
    hostname: unboxed_frontend
    domainname: unboxed_frontend.local
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.build
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=$NODE_ENV
      - REACT_APP_API_ENDPOINT=$UNBOXED_API_ENDPOINT
      - REACT_APP_UNBOXED_MAGIC_LINK_PUBLISHABLE_API_KEY=$UNBOXED_MAGIC_LINK_PUBLISHABLE_API_KEY
      - REACT_APP_SQUARE_LOCATION_ID=$UNBOXED_SQUARE_LOCATION_ID
      - PATH=/frontend/node_modules/.bin:$PATH
    depends_on:
      - database
      - backend
    command: start
  database:
    container_name: "unboxed_database"
    hostname: unboxed_database
    domainname: unboxed_database.local
    image: "mongo"
    # command: mongod --auth
    volumes:
      - ./database:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_DATABASE=$UNBOXED_MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$UNBOXED_MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$UNBOXED_MONGODB_PASSWORD
  backend:
    container_name: "unboxed_backend"
    hostname: unboxed_backend
    domainname: unboxed_backend.local
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=$NODE_ENV
      - MAGIC_LINK_SECRET_KEY=$UNBOXED_MAGIC_LINK_SECRET_KEY
      - SQUARE_SIGNATURE_KEY=$UNBOXED_SQUARE_SIGNATURE_KEY
      - PORT=8000
      - ENVIRONMENT=$UNBOXED_SQUARE_ENVIRONMENT
      - SQUARE_ACCESS_TOKEN=$UNBOXED_SQUARE_ACCESS_TOKEN
      - SQUARE_LOCATION_ID=$UNBOXED_SQUARE_LOCATION_ID
      - SQUARE_API_VERSION=$UNBOXED_SQUARE_API_VERSION
      - DB_HOST=unboxed_database
      - DB_USER=$UNBOXED_MONGODB_USER
      - DB_PASSWORD=$UNBOXED_MONGODB_PASSWORD
      - DB_NAME=$UNBOXED_MONGODB_DATABASE
      - DB_PORT=$UNBOXED_MONGODB_DOCKER_PORT
    depends_on:
      - database
    # stdin_open: true
    # tty: true
volumes:
  database:
    driver: local

